name: musclequant
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-image
  - scipy
  - tifffile
  - qtpy
  - pyqt
  - pip
  - pip:
      - napari[all]
      - magicgui
      - cellpose
      - torch
